name: go-observability

services:
  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    container_name: inventory-service
    ports:
      - "8001:8080"
    environment:
      - SERVICE_NAME=inventory-service
      - SERVICE_PORT=8080
      - OTEL_ENDPOINT=otel-collector:4318
    depends_on:
      - otel-collector
    networks:
      - observability
    develop:
      watch:
        - action: rebuild
          path: ./inventory-service
        - action: rebuild
          path: ./go.mod
        - action: rebuild
          path: ./go.sum

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    ports:
      - "8003:8080"
    environment:
      - SERVICE_NAME=payment-service
      - SERVICE_PORT=8080
      - OTEL_ENDPOINT=otel-collector:4318
    depends_on:
      - otel-collector
    networks:
      - observability
    develop:
      watch:
        - action: rebuild
          path: ./payment-service
        - action: rebuild
          path: ./go.mod
        - action: rebuild
          path: ./go.sum

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "8002:8080"
    environment:
      - SERVICE_NAME=order-service
      - SERVICE_PORT=8080
      - OTEL_ENDPOINT=otel-collector:4318
      - INVENTORY_BASE_URL=http://inventory-service:8080
      - PAYMENT_BASE_URL=http://payment-service:8080
    depends_on:
      - otel-collector
      - inventory-service
      - payment-service
    networks:
      - observability
    develop:
      watch:
        - action: rebuild
          path: ./order-service
        - action: rebuild
          path: ./go.mod
        - action: rebuild
          path: ./go.sum

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel/collector-config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    ports:
      - "4318:4318" # OTLP HTTP
      - "8889:8889" # Prometheus scrape endpoint
    networks:
      - observability

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
    networks:
      - observability

networks:
  observability:
    driver: bridge
